### ISSUE TITLE
nix-review fails with HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by jtojnar** [Mic92/nix-review#1]
I tried running `nix-review` installed from nixpkgs master but it fails with the following error:

```ShellSession
$ cd ~/Projects/nixpkgs
$ result/bin/nix-review pr 39714 
$ git worktree prune
Traceback (most recent call last):
  File "/nix/store/7qk6dqyfqh7s2835wcaqs7ri6mrqwbsw-nix-review-0.1.2/bin/..nix-review-wrapped-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/7qk6dqyfqh7s2835wcaqs7ri6mrqwbsw-nix-review-0.1.2/lib/python3.6/site-packages/nix_review/app.py", line 106, in main
    real_main(command, args)
  File "/nix/store/7qk6dqyfqh7s2835wcaqs7ri6mrqwbsw-nix-review-0.1.2/lib/python3.6/site-packages/nix_review/app.py", line 99, in real_main
    args.func(args)
  File "/nix/store/7qk6dqyfqh7s2835wcaqs7ri6mrqwbsw-nix-review-0.1.2/lib/python3.6/site-packages/nix_review/app.py", line 15, in pr_command
    r.review_pr(args.number)
  File "/nix/store/7qk6dqyfqh7s2835wcaqs7ri6mrqwbsw-nix-review-0.1.2/lib/python3.6/site-packages/nix_review/review.py", line 65, in review_pr
    pr = json.load(urllib.request.urlopen(api_url))
  File "/nix/store/96wn2gz3mwi71gwcrvpfg39bsymd7gqx-python3-3.6.5/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/nix/store/96wn2gz3mwi71gwcrvpfg39bsymd7gqx-python3-3.6.5/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/nix/store/96wn2gz3mwi71gwcrvpfg39bsymd7gqx-python3-3.6.5/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/nix/store/96wn2gz3mwi71gwcrvpfg39bsymd7gqx-python3-3.6.5/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/nix/store/96wn2gz3mwi71gwcrvpfg39bsymd7gqx-python3-3.6.5/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/nix/store/96wn2gz3mwi71gwcrvpfg39bsymd7gqx-python3-3.6.5/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by jtojnar** [comment]
Right, that is probably it. Would it be possible to use a bearer token for the API calls?

**Comment by Mic92** [comment]
fixed in https://github.com/Mic92/nix-review/pull/2
