### ISSUE TITLE
error on https://github.com/NixOS/nixpkgs/pull/52524

### ISSUE THREAD

**Issue by stephengroat** [Mic92/nix-review#32]
```
# nix-review rev HEAD
$ git fetch --force https://github.com/NixOS/nixpkgs master:refs/nix-review/0
remote: Enumerating objects: 1, done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 1
Unpacking objects: 100% (1/1), done.
From https://github.com/NixOS/nixpkgs
 * [new branch]              master     -> refs/nix-review/0
 * [new tag]                 18.09-beta -> 18.09-beta
$ git worktree add /root/.cache/nix-review/rev-72d3636960f6b9bb0b7b360af236e4beaffd9310/nixpkgs b0f9e472712b66613ac1f7703d3c914f35f7a1af
Preparing worktree (detached HEAD b0f9e472712)
Checking out files: 100% (17894/17894), done.
HEAD is now at b0f9e472712 ip2unix: 1.2.0 -> 2.0.0
$ git worktree prune
Traceback (most recent call last):
  File "/nix/store/s85c2s91m1nhq17rwig8niyslpsdp1q3-nix-review-1.0.1/bin/.nix-review-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/s85c2s91m1nhq17rwig8niyslpsdp1q3-nix-review-1.0.1/lib/python3.7/site-packages/nix_review/__init__.py", line 10, in main
    cli.main(command, args)
  File "/nix/store/s85c2s91m1nhq17rwig8niyslpsdp1q3-nix-review-1.0.1/lib/python3.7/site-packages/nix_review/cli/__init__.py", line 119, in main
    args.func(args)
  File "/nix/store/s85c2s91m1nhq17rwig8niyslpsdp1q3-nix-review-1.0.1/lib/python3.7/site-packages/nix_review/cli/rev.py", line 25, in rev_command
    review.review_commit(args.branch, commit)
  File "/nix/store/s85c2s91m1nhq17rwig8niyslpsdp1q3-nix-review-1.0.1/lib/python3.7/site-packages/nix_review/review.py", line 121, in review_commit
    self.start_review(self.build_commit(branch_rev, reviewed_commit))
  File "/nix/store/s85c2s91m1nhq17rwig8niyslpsdp1q3-nix-review-1.0.1/lib/python3.7/site-packages/nix_review/review.py", line 63, in build_commit
    base_packages = list_packages(str(self.worktree_dir()))
  File "/nix/store/s85c2s91m1nhq17rwig8niyslpsdp1q3-nix-review-1.0.1/lib/python3.7/site-packages/nix_review/review.py", line 136, in list_packages
    for (event, elem) in context:
  File "/nix/store/6lm4gi5iv8fbf1b1mm6g3gfnnv63f1gn-python3-3.7.1/lib/python3.7/xml/etree/ElementTree.py", line 1228, in iterator
    root = pullparser._close_and_return_root()
  File "/nix/store/6lm4gi5iv8fbf1b1mm6g3gfnnv63f1gn-python3-3.7.1/lib/python3.7/xml/etree/ElementTree.py", line 1275, in _close_and_return_root
    root = self._parser.close()
xml.etree.ElementTree.ParseError: no element found: line 60102, column 0
```

**Comment by Mic92** [comment]
I can not reproduce your error. Is it possible that your `nix-review` run out of memory? Is it reproducible? In that case please send me the output of: `nix-env -f . -qaP --xml --out-path --show-trace > packages.xml`

**Comment by stephengroat** [comment]
[packages.txt](https://github.com/Mic92/nix-review/files/2754152/packages.txt)

**Comment by Mic92** [comment]
When I run the same code on the file you have provided
it runs through without parsing error:

```
import xml.etree.ElementTree as ET

packages = []
with open("./packages.txt") as f:
    context = ET.iterparse(f, events=("start",))
    packages = set()
    for (event, elem) in context:
        if elem.tag == "item":
            attrib = elem.attrib["attrPath"]
        elif elem.tag == "output":
            assert attrib is not None
            path = elem.attrib["path"]
            packages.add((attrib, path))
```

**Comment by stephengroat** [comment]
cannot replicate on newer versions
