### ISSUE TITLE
"already exists. Is a different review already running?"

### ISSUE THREAD

**Issue by teto** [Mic92/nix-review#47]
I've hit this a couple of times already with no background nix-review working. How can I force nix-review to ignore things ?

```
(ins)[teto@jedha:~/nixpkgs3]$ nix-review rev HEAD
/home/teto/.cache/nix-review/rev-bc84ba0d802d3095e0e64cbf19fb83e8e2840993/nixpkgs already exists. Is a different review already running?
Traceback (most recent call last):
  File "/nix/store/jyxbl0k4vv85928mhl72c70ikglz0491-nix-review-1.0.5/bin/.nix-review-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/jyxbl0k4vv85928mhl72c70ikglz0491-nix-review-1.0.5/lib/python3.7/site-packages/nix_review/__init__.py", line 10, in main
    cli.main(command, args)
  File "/nix/store/jyxbl0k4vv85928mhl72c70ikglz0491-nix-review-1.0.5/lib/python3.7/site-packages/nix_review/cli/__init__.py", line 119, in main
    args.func(args)
  File "/nix/store/jyxbl0k4vv85928mhl72c70ikglz0491-nix-review-1.0.5/lib/python3.7/site-packages/nix_review/cli/rev.py", line 18, in rev_command
    with Builddir(f"rev-{commit}") as builddir:
  File "/nix/store/jyxbl0k4vv85928mhl72c70ikglz0491-nix-review-1.0.5/lib/python3.7/site-packages/nix_review/builddir.py", line 53, in __init__
    os.makedirs(self.worktree_dir)
  File "/nix/store/b75brsgimlrw33l9ykhacz5fni3vq0jn-python3-3.7.2/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/teto/.cache/nix-review/rev-bc84ba0d802d3095e0e64cbf19fb83e8e2840993/nixpkgs'

```

Also the help doesn't show all options (like -p or --builder-args)

**Comment by Mic92** [comment]
There is currently no workaround for this. Currently the directory name of the 
review will be calculated from pr number or commit hash.
You probably have a different shell open with the same nix-review hash.
If that is not the case, delete the directory.

**Comment by Mic92** [comment]
Should be fixed in the latest release.
